### ISSUE TITLE
Backend error - Missing leading slash in namespace declaration

### ISSUE THREAD

**Issue by derBoogie** [franzholz/imagecycle#3]
Hi,

I got the following error when opening the TypoScript Contants Editor:

Class 'TYPO3Extension\Imagecycle\Backend\TYPO3Extension\Imagecycle\Backend\ItemsProcFunc' not found

As you can see, the namespace "TYPO3Extension\Imagecycle\Backend\" is used twice.

The solution is to add a leading slash in imagecycle/Classes/Backend/ExtensionManagerConfiguration.php in line 51:

$itemsProcFunc = GeneralUtility::makeInstance(\TYPO3Extension\Imagecycle\Backend\ItemsProcFunc::class);

(TYPO3 v7.6.55, imagecycle v3.2.2, PHP v7.2-latest FPM)

**Comment by franzholz** [comment]
This issue has been fixed now in version 3.3.0
